# Generated by Django 5.2.1 on 2025-06-27 18:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTienda', models.CharField(max_length=200)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('DescripcionTienda', models.TextField(blank=True)),
                ('Cant_productos', models.PositiveIntegerField(default=0)),
                ('Cant_seguidores', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomCat', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='productoDescription',
            new_name='DescripcionProd',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='productoImage',
            new_name='FotoProd',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='productoName',
            new_name='Nomprod',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='productoPrice',
            new_name='Precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='FechaPub',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='Stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('valortotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PagaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('productoComprado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDeseado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tienda', verbose_name='Tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
        migrations.AddField(
            model_name='tienda',
            name='Propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Propietario'),
        ),
        migrations.AddIndex(
            model_name='seguimientotienda',
            index=models.Index(fields=['usuario', 'tienda'], name='api_seguimi_usuario_9536aa_idx'),
        ),
        migrations.AddIndex(
            model_name='productodeseado',
            index=models.Index(fields=['usuario', 'producto'], name='api_product_usuario_a5fae7_idx'),
        ),
        migrations.AddIndex(
            model_name='pagaproducto',
            index=models.Index(fields=['comprador', 'productoComprado'], name='api_pagapro_comprad_757424_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario', 'producto'], name='api_carrito_usuario_0bb7b2_idx'),
        ),
    ]
