# Generated by Django 5.2.1 on 2025-06-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_persona_id_producto_tienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tienda',
        ),
    ]
