# Generated by Django 5.2.1 on 2025-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_persona_id_alter_persona_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Correo'),
        ),
    ]
