# Generated by Django 5.2.1 on 2025-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_persona_id_alter_persona_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
    ]
