# Generated by Django 5.2.1 on 2025-06-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_persona_id_alter_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
    ]
