# Generated by Django 5.2.1 on 2025-06-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_persona_tienda_tipocategoria_remove_venta_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagaProducto',
            new_name='Venta',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='api_venta_comprad_d45e5f_idx',
            old_name='api_pagapro_comprad_757424_idx',
        ),
    ]
