# Generated by Django 5.2.1 on 2025-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_pagaproducto_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='vacio_', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Estado',
            field=models.BooleanField(default=False),
        ),
    ]
